#!/usr/bin/env python3

from getpass import getpass
from enum import Enum
import shutil
import subprocess


class OS(Enum):
    Fedora = 1
    Ubuntu = 2
    Proxmox = 3
    LXC_Debian = 4


class Server:
    def __init__(self, ip, os, user, nickname, docker_path=""):
        self.ip = ip
        self.os = os
        self.user = user
        self.nickname = nickname
        self.docker_path = docker_path

    def __str__(self):
        return f"{self.user}@{self.ip} ({self.os})"


servers = [
    Server("192.168.68.112", OS.Proxmox, "leah", "PVE Hypervisor"),
    Server("192.168.68.129", OS.LXC_Debian, "root", "The Lounge"),
    Server("192.168.68.109", OS.LXC_Debian, "root", "Wireguard"),
    #    Temporarily disable deluge, I need to figure out mounting my NAS.
    #    Server("192.168.68.130", OS.LXC_Debian, "root", "Deluge"),
    Server("192.168.68.114", OS.Fedora, "leah", "Alpha Proxy"),
    Server("192.168.68.107", OS.Fedora, "leah", "Alpha Wiki"),
    Server("192.168.68.120", OS.Ubuntu, "leah", "Jellyfin"),
    Server("192.168.68.126", OS.Fedora, "leah", "Miniflux"),
]


def main():
    if not shutil.which("sshpass"):
        print("You need sshpass!!!")
        exit(1)
    failed_servers = []
    # I use the same password for them all XD
    password = getpass("Password for servers: ")
    for server in servers:
        print(f" [I] Updating {server}!")
        update_cmds = []
        match server.os:
            case OS.Fedora:
                update_cmds = [f"echo {password} | sudo -S dnf update -y"]
            case OS.Ubuntu:
                update_cmds = [
                    f"echo {password} | sudo -S apt update",
                    f"echo {password} | sudo -S apt dist-upgrade -y",
                ]
            case OS.Proxmox:
                update_cmds = [
                    f"echo {password} | sudo -S apt update",
                    f"echo {password} | sudo -S apt dist-upgrade -y",
                ]
            case OS.LXC_Debian:
                update_cmds = ["apt update", "apt dist-upgrade -y"]
        for update_cmd in update_cmds:
            cmd = [
                "sshpass",
                f"-p{password}",
                "ssh",
                "-t",
                f"{server.user}@{server.ip}",
                update_cmd,
            ]
            print(f" [V] Running: {str(cmd).replace(password, '__PASSWORD__')}")
            proc = subprocess.run(cmd)
        if proc.returncode != 0:
            print(f" [E] Server {server} failed!")
            failed_servers.append(server)
        print(f" [I] Done with {server}!")
    if len(failed_servers) != 0:
        print(f" [E] {str(len(failed_servers))} servers failed! Failed servers:")
        for server in failed_servers:
            print(f"      - {server}")
        print(" [I] Chances are, You don't have it authorized in ~/.ssh/known_hosts")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n:(")
    exit(0)
