#!/usr/bin/env python3

import getpass
import os
import platform
import shutil
import subprocess


def os_not_supported_error():
    print(" [!] Sorry, Your OS isn't supported.")
    print("     If you have the time, please ")
    print("     contribute an update snippet at:")
    print("     https://github.com/RealFX-Code/scripts")
    exit(1)


def find_elevation():
    if getpass.getuser() == "root" or getpass.getuser() == "Administrator":
        return ""
    elif shutil.which("sudo"):
        return "sudo"
    elif shutil.which("doas"):
        return "doas"
    else:
        print(" [W] No elevation method was detected as installed,")
        print("     And you're not running as ROOT.")
        print("     ")
        print("     THINGS MAY BREAK!")
        print("     ")
        return ""


def handle_linux_update():
    def do_arch_update():
        if shutil.which("paru"):
            print(" [I] Paru update")
            _ = subprocess.run(["paru"])
        elif shutil.which("yay"):
            print(" [I] Yay update")
            _ = subprocess.run(["yay"])
        else:
            # Fallback to regular Pacman
            print(" [W] No AUR Helper was found!")
            print("     You won't get AUR Updates from sysup.")
            print(" [I] Pacman update")
            _ = subprocess.run([find_elevation(), "pacman", "-Syyuu"])
        exit(0)

    def do_debian_update():
        elevation = find_elevation()
        _ = subprocess.run([elevation, "apt", "update"])
        _ = subprocess.run([elevation, "apt", "upgrade"])
        _ = subprocess.run([elevation, "apt", "autoremove"])
        exit(0)

    def do_fedora_update():
        elevation = find_elevation()
        _ = subprocess.run([elevation, "dnf", "update"])
        exit(0)

    def do_gentoo_update():
        elevation = find_elevation()
        _ = subprocess.run([elevation, "emaint", "--auto", "sync"])
        _ = subprocess.run([elevation, "emerge", "-avuDNU", "--with-bdeps=y", "@world"])
        _ = subprocess.run([elevation, "emerge", "-ac"])
        exit(0)

    def do_nixos_update():
        elevation = find_elevation()
        if os.path.isfile("/etc/nixos/flake.nix"):
            _ppwd = os.getcwd()
            os.chdir("/etc/nixos")
            _ = subprocess.run([elevation, "nix", "flake", "update"])
            os.chdir(_ppwd)
        _ = subprocess.run([elevation, "nixos-rebuild", "switch", "--upgrade"])
        exit(0)

    distro = platform.freedesktop_os_release()["NAME"]

    match distro:
        case "Arch Linux" | "Artix" | "CachyOS Linux" | "EndeavourOS":
            print(" [I] Arch-based OS Update")
            do_arch_update()
        case "Debian GNU/Linux" | "Trisquel" | "Ubuntu":
            print(" [I] Debian-based OS Update")
            do_debian_update()
        case "Fedora Linux":
            do_fedora_update()
        case "Gentoo" | "Funtoo":
            print(" [I] Gentoo-based OS Update")
            do_gentoo_update()
        case "NixOS":
            print(" [I] NixOS Update")
            do_nixos_update()
        case _:
            print(" [F] Your distro isn't supported!")
            print("     Current distro: " + distro)
            os_not_supported_error()


def handle_freebsd_update():
    elevation = find_elevation()
    _ = subprocess.run([elevation, "pkg", "update"])
    _ = subprocess.run([elevation, "pkg", "upgrade"])
    exit(0)


def handle_windows_update():
    # This is only for "windows-native" package managers;
    # That means that cygwin or msys2 doesn't count.
    #
    # Windows' quirks:
    #  - No admin need for most package managers,
    #    They'll ask for it themselvs.
    #
    has_updated = False
    if shutil.which("winget"):
        print(" [I] Upgrading with winget...")
        _ = subprocess.run(
            ["winget", "upgrade", "--all", "--verbose", "--include-unknown"]
        )
        has_updated = True
    if shutil.which("scoop"):
        print(" [I] Upgrading with scoop...")
        _ = subprocess.run(["scoop", "update", "*"])
        has_updated = True
    if shutil.which("choco"):
        print(" [I] Upgrading with choco...")
        _ = subprocess.run(["choco", "upgrade", "all"])
        has_updated = True

    if has_updated:
        exit(0)
    else:
        print(" [W] Didn't update, as no package manager was found!")
        exit(1)


def handle_darwin_update():
    has_updated = False
    if shutil.which("softwareupdate"):
        print(" [I] Forcing system update check...")
        _ = subprocess.run(["softwareupdate", "-l"])
        has_updated = True

    if shutil.which("brew"):
        print(" [I] Updating homebrew...")
        brew_update_steps = ["update", "upgrade", "autoremove", "cleanup", "doctor"]
        for step in brew_update_steps:
            _ = subprocess.run(["brew", step])
        has_updated = True
    if has_updated:
        exit(0)
    else:
        print(" [W] No updates were done.")
        exit(1)


def main():
    print("      _____   _____ _   _ ___ ")
    print("     / __\\ \\ / / __| | | | _ \\")
    print("     \\__ \\\\ V /\\__ \\ |_| |  _/")
    print("     |___/ |_| |___/\\___/|_|  ")
    print("")
    match platform.system():
        case "Linux":
            handle_linux_update()
        case "FreeBSD":
            handle_freebsd_update()
        case "Darwin":
            handle_darwin_update()
        case "Windows":
            handle_windows_update()
        case _:
            print(" [F] Your platform isn't supported!")
            print("     Platform: " + platform.system())
            os_not_supported_error()
    print("Somehow, Nothing happened!")
    exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        # CTRL+C shouldn't trigger an exception!
        exit(0)
